### ISSUE TITLE
Page not found when uploading a new dataset

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-study-data-access#21]
When a new user dataset is uploaded and installed, the user gets a **Page not found** when clicking on the **Explore in ClinEpiDB** link on the user dataset detail page. ~This is most likely due to how we store the list of studies in IndexedDB.~

**Comment by dmfalke** [comment]
The issue has to do with memoization done by https://github.com/VEuPathDB/web-study-data-access/blob/538bf13f0c64f4999ff0c143cc2cf11f45c98872/src/data-restriction/permissionsHooks.ts#L23-L40.

**Comment by dmfalke** [comment]
This should be fixed on qa sites. It will be deployed to live sites once it has been tested with release branch code, which I believe @aurreco-uga will be handling.

**Comment by SheenaTomko** [comment]
Looks good on QA. Dave sees it in the build 59 branch
